package edu.isel.pdm.memorymatrix.game.history

import androidx.lifecycle.LiveData
import androidx.room.Dao
import androidx.room.Insert
import androidx.room.Query

/**
 * Specifies the contract to be supported by the DAO associated to the [GameResult] entity. The
 * DAO implementation is to be automatically generated by Room build tools.
 */
@Dao
interface GameResultDao {

    @Query("SELECT * FROM games ORDER BY date DESC")
    fun loadAllGames(): List<GameResult>

    @Query("SELECT * FROM games ORDER BY date DESC LIMIT :count")
    fun loadLastGames(count: Int): LiveData<List<GameResult>>

    @Insert
    fun insertGame(game: GameResult)
}